name: Update Fork
on: 
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Stats
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event. "
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checkout preset
        uses: actions/checkout@v3
        with:
          repository: laravel-frontend-presets/paper-dashboard
          token: ${{ secrets.CT_TOKEN }}
      - run: |
          git config --global user.name "CI Bot"
          git config --global user.email "team@mupdivision.com"
          git remote add upstream https://${{ secrets.CT_TOKEN }}@github.com/creativetimofficial/paper-dashboard-laravel
          git fetch --all
          git pull origin master --tags -f
          git checkout upstream/master
          git pull upstream master
          git checkout origin/master
          git merge upstream/master
          git push origin HEAD:master --force
          git push --tags
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          repository: creativetimofficial/paper-dashboard-laravel
          token: ${{ secrets.CT_TOKEN }}
      - run: |
          git config --global user.name "CI Bot"
          git config --global user.email "team@mupdivision.com"
          git remote add upstream https://${{ secrets.CT_TOKEN }}@github.com/laravel-frontend-presets/paper-dashboard
          git fetch --all
          git pull origin master --tags -f
          git checkout upstream/master
          git pull upstream master
          git checkout origin/master
          git merge upstream/master
          git push origin HEAD:master --force
          git push --tags
      - run: echo "The fork was updated"   